# Generated by Django 3.1.4 on 2021-01-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=2000)),
                ('Status', models.SmallIntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"Application"',
            },
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Module', models.TextField()),
                ('Parameters', models.TextField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"ApplicationLog"',
            },
        ),
        migrations.CreateModel(
            name='ExceptionLog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('File', models.TextField()),
                ('Description', models.TextField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"ExceptionLog"',
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=2000)),
                ('PaymentTerms', models.SmallIntegerField()),
                ('CycleInMonths', models.IntegerField()),
                ('Status', models.SmallIntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"LicenseType"',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ExternalRef', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('PhoneNo', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
                ('Picture', models.BinaryField()),
                ('Status', models.SmallIntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"Provider"',
            },
        ),
        migrations.CreateModel(
            name='ProviderLicense',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UniqueCode', models.CharField(max_length=100)),
                ('StartDate', models.DateTimeField()),
                ('IsUnitsApplicable', models.SmallIntegerField()),
                ('NoOfUnits', models.IntegerField()),
                ('Status', models.SmallIntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('ApplicationRef', models.ForeignKey(db_column='ApplicationRef', on_delete=django.db.models.deletion.CASCADE, to='Core.application')),
                ('LicenseTypeRef', models.ForeignKey(db_column='LicenseTypeRef', on_delete=django.db.models.deletion.CASCADE, to='Core.licensetype')),
                ('ProviderRef', models.ForeignKey(db_column='ProviderRef', on_delete=django.db.models.deletion.CASCADE, to='Core.provider')),
            ],
            options={
                'db_table': '"ProviderLicense"',
            },
        ),
    ]
